services:
  - type: web
    name: haderech-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: haderech-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "haderech-portal.onrender.com"
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: haderech-db
    plan: free
    databaseName: haderech_smrps
    user: haderech_user
